apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: awsinfra-eks
spec:
  compositeTypeRef:
    apiVersion: aws.kfo.io/v1alpha1
    kind: awsinfra
  mode: Pipeline
  pipeline:
  - step: cluster-creation
    functionRef:
      name: crossplane-contrib-function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:

      - name: eks-cluster
        base:
          apiVersion: eks.aws.m.upbound.io/v1beta1
          kind: Cluster
          metadata:
            name: cluster-name-placeholder
            namespace: upbound-namespace-placeholder
          spec:
            forProvider:
              accessConfig:
                authenticationMode: API_AND_CONFIG_MAP
              region: aws-region-placeholder
              version: eks-version-placeholder
              roleArnRef:
                name: eks-cluster-role-placeholder
                namespace: upbound-namespace-placeholder
              tags:
                karpenter.sh/discovery: eks-cluster-name-placeholder
              vpcConfig:
                subnetIdSelector:
                  matchLabels:
                    aws.kfo.io/subnet-type: private
                    aws.kfo.io/cluster-name: cluster-name-placeholder
        patches:
          - type: FromCompositeFieldPath
            fromFieldPath: spec.cluster_name
            toFieldPath: metadata.name
          - fromFieldPath: spec.upbound_namespace
            toFieldPath: metadata.namespace         
          - type: FromCompositeFieldPath
            fromFieldPath: spec.aws_region
            toFieldPath: spec.forProvider.region   
          - fromFieldPath: spec.k8s_version
            toFieldPath: spec.forProvider.version
          - type: FromCompositeFieldPath
            fromFieldPath: spec.cluster_name
            toFieldPath: spec.forProvider.tags[karpenter.sh/discovery]
          - type: FromCompositeFieldPath
            fromFieldPath: spec.cluster_name
            toFieldPath: spec.forProvider.vpcConfig.subnetIdSelector.matchLabels[aws.kfo.io/cluster-name]       
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.cluster_name
              strategy: string
              string:
                fmt: "service-role-%s"
            toFieldPath: spec.forProvider.roleArnRef.name
          - type: FromCompositeFieldPath
            fromFieldPath: spec.upbound_namespace
            toFieldPath: spec.forProvider.roleArnRef.namespace                         

      - name: node-group 
        base:
          apiVersion: eks.aws.m.upbound.io/v1beta1
          kind: NodeGroup
          metadata:
            name: eks-node-group-name-placeholder
            namespace: upbound-namespace-placeholder
          spec:
            forProvider:
              launchTemplate:
                name: eks-launch-template-name-placeholder #TODO: create thye patch for this
                version: 1
              subnetIdRefs:
                - name: eks-private-subnet-1-placeholder
                  namespace: upbound-namespace-placeholder
                - name: eks-private-subnet-2-placeholder
                  namespace: upbound-namespace-placeholder
              instanceTypes: [m5.large]
              clusterNameRef:
                name: eks-cluster-name-placeholder
                namespace: upbound-namespace-placeholder
              nodeRoleArnRef:
                name: eks-node-role-name-placeholder
                namespace: upbound-namespace-placeholder
              region: region-placeholder
              scalingConfig:
                desiredSize: 2
                maxSize: 3
                minSize: 1
        patches:
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.cluster_name
              strategy: string
              string:
                fmt: "%s-ng"
            toFieldPath: metadata.name
          - fromFieldPath: spec.upbound_namespace
            toFieldPath: metadata.namespace         
          - fromFieldPath: spec.cluster_name
            toFieldPath: spec.forProvider.clusterNameRef.name
          - fromFieldPath: spec.upbound_namespace
            toFieldPath: spec.forProvider.clusterNameRef.namespace
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.cluster_name
              strategy: string
              string:
                fmt: "node-role-%s"
            toFieldPath: spec.forProvider.nodeRoleArnRef.name
          - fromFieldPath: spec.upbound_namespace
            toFieldPath: spec.forProvider.nodeRoleArnRef.namespace
          - type: FromCompositeFieldPath
            fromFieldPath: spec.aws_region
            toFieldPath: spec.forProvider.region
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.cluster_name
              strategy: string
              string:
                fmt: "subnet-private-use1c-%s"
            toFieldPath: spec.forProvider.subnetIdRefs[0].name

          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.cluster_name
              strategy: string
              string:
                fmt: "subnet-private-use1d-%s"
            toFieldPath: spec.forProvider.subnetIdRefs[1].name

          # Namespace correcto en ambas refs
          - fromFieldPath: spec.upbound_namespace
            toFieldPath: spec.forProvider.subnetIdRefs[0].namespace

          - fromFieldPath: spec.upbound_namespace
            toFieldPath: spec.forProvider.subnetIdRefs[1].namespace

      - name: karpenter-node-access-entry
        base:
          apiVersion: eks.aws.m.upbound.io/v1beta1
          kind: AccessEntry
          metadata:
            name: accessentry-placeholder
            namespace: upbound-namespace-placeholder
          spec:
            forProvider:
              region: region-placeholder
              clusterNameRef:
                name: eks-cluster-name-placeholder
                namespace: upbound-namespace-placeholder
              principalArnFromRoleRef:
                name: karpenter-node-role-placeholder
                namespace: upbound-namespace-placeholder
                #matchControllerRef: false
              type: STANDARD
        patches:
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.cluster_name
              strategy: string
              string:
                fmt: "karpenter-node-access-%s"
            toFieldPath: metadata.name

          - fromFieldPath: spec.upbound_namespace
            toFieldPath: metadata.namespace

          - fromFieldPath: spec.cluster_name
            toFieldPath: spec.forProvider.clusterNameRef.name

          - fromFieldPath: spec.upbound_namespace
            toFieldPath: spec.forProvider.clusterNameRef.namespace

          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.cluster_name
              strategy: string
              string:
                fmt: "node-role-%s"
            toFieldPath: spec.forProvider.principalArnFromRoleRef.name

          - fromFieldPath: spec.upbound_namespace
            toFieldPath: spec.forProvider.principalArnFromRoleRef.namespace
          
          - fromFieldPath: spec.aws_region
            toFieldPath: spec.forProvider.region


      - name: karpenter-pod-identity
        base:
          apiVersion: eks.aws.m.upbound.io/v1beta1
          kind: PodIdentityAssociation
          metadata:
            name: podidentity-placeholder
            namespace: upbound-namespace-placeholder
          spec:
            forProvider:
              clusterName: cluster-placeholder
              namespace: kube-system
              serviceAccount: karpenter
              roleArnRef:
                name: karpenter-controller-role-placeholder
                namespace: upbound-namespace-placeholder
              region: region-placeholder
        patches:
          # nombre dinámico
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.cluster_name
              strategy: string
              string:
                fmt: "pod-identity-%s"
            toFieldPath: metadata.name

          - fromFieldPath: spec.upbound_namespace
            toFieldPath: metadata.namespace

          - fromFieldPath: spec.cluster_name
            toFieldPath: spec.forProvider.clusterName

          - fromFieldPath: spec.aws_region
            toFieldPath: spec.forProvider.region

          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.cluster_name
              strategy: string
              string:
                fmt: "karpenter-controller-role-%s"
            toFieldPath: spec.forProvider.roleArnRef.name

          - fromFieldPath: spec.upbound_namespace
            toFieldPath: spec.forProvider.roleArnRef.namespace

      - name: pod-identity-addon
        base:        
          apiVersion: eks.aws.m.upbound.io/v1beta1
          kind: Addon
          metadata:
            name: eks-pod-identity-agent
            namespace: upbound-namespace-placeholder
          spec:
            forProvider:
              addonName: eks-pod-identity-agent
              clusterName: cluster-name-placeholder
              region: region-placeholder
        patches:
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.cluster_name
              strategy: string
              string:
                fmt: "identity-agent-%s"
            toFieldPath: metadata.name
          - fromFieldPath: spec.upbound_namespace
            toFieldPath: metadata.namespace
          - type: FromCompositeFieldPath
            fromFieldPath: spec.cluster_name
            toFieldPath: spec.forProvider.clusterName
          - type: FromCompositeFieldPath
            fromFieldPath: spec.aws_region
            toFieldPath: spec.forProvider.region

      - name: metrics-server-addon
        base:        
          apiVersion: eks.aws.m.upbound.io/v1beta1
          kind: Addon
          metadata:
            name: eks-metrics-server
            namespace: upbound-namespace-placeholder
          spec:
            forProvider:
              addonName: metrics-server
              clusterName: cluster-name-placeholder
              region: region-placeholder
        patches:
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.cluster_name
              strategy: string
              string:
                fmt: "metrics-server-%s"
            toFieldPath: metadata.name
          - fromFieldPath: spec.upbound_namespace
            toFieldPath: metadata.namespace
          - type: FromCompositeFieldPath
            fromFieldPath: spec.cluster_name
            toFieldPath: spec.forProvider.clusterName
          - type: FromCompositeFieldPath
            fromFieldPath: spec.aws_region
            toFieldPath: spec.forProvider.region            

      - name: coredns-addon
        base:        
          apiVersion: eks.aws.m.upbound.io/v1beta1
          kind: Addon
          metadata:
            name: eks-coredns
            namespace: upbound-namespace-placeholder
          spec:
            forProvider:
              addonName: coredns
              clusterName: cluster-name-placeholder
              region: region-placeholder
        patches:
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.cluster_name
              strategy: string
              string:
                fmt: "coredns-%s"
            toFieldPath: metadata.name
          - fromFieldPath: spec.upbound_namespace
            toFieldPath: metadata.namespace
          - type: FromCompositeFieldPath
            fromFieldPath: spec.cluster_name
            toFieldPath: spec.forProvider.clusterName
          - type: FromCompositeFieldPath
            fromFieldPath: spec.aws_region
            toFieldPath: spec.forProvider.region                 

      - name: kube-proxy-addon
        base:        
          apiVersion: eks.aws.m.upbound.io/v1beta1
          kind: Addon
          metadata:
            name: eks-kube-proxy
            namespace: upbound-namespace-placeholder
          spec:
            forProvider:
              addonName: kube-proxy
              clusterName: cluster-name-placeholder
              region: region-placeholder
        patches:
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.cluster_name
              strategy: string
              string:
                fmt: "kube-proxy-%s"
            toFieldPath: metadata.name
          - fromFieldPath: spec.upbound_namespace
            toFieldPath: metadata.namespace
          - type: FromCompositeFieldPath
            fromFieldPath: spec.cluster_name
            toFieldPath: spec.forProvider.clusterName
          - type: FromCompositeFieldPath
            fromFieldPath: spec.aws_region
            toFieldPath: spec.forProvider.region     

 