#TODO: Implement a patchset

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: awsinfra-iam
spec:
  compositeTypeRef:
    apiVersion: aws.kfo.io/v1alpha1
    kind: awsinfra
  mode: Pipeline
  pipeline:

  - step: role-creation
    functionRef:
      name: crossplane-contrib-function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - name: karpenter-node-role
        base:
          apiVersion: iam.aws.m.upbound.io/v1beta1
          kind: Role
          metadata:
            annotations:
              meta.upbound.io/example-id: iam/v1beta1/rolepolicy
          spec:
            forProvider:
              assumeRolePolicy: |
                {
                    "Version": "2012-10-17",
                    "Statement": [
                        {
                            "Effect": "Allow",
                            "Principal": {
                                "Service": "ec2.amazonaws.com"
                            },
                            "Action": "sts:AssumeRole"
                        }
                    ]
                }
        patches:
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.cluster_name
              strategy: string
              string:
                fmt: "karpenter-node-role-%s"
            toFieldPath: metadata.name
          - type: FromCompositeFieldPath
            fromFieldPath: spec.upbound_namespace
            toFieldPath: metadata.namespace


  - step: role-policy-attachments
    functionRef:
      name: crossplane-contrib-function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:

      - name: karpenter-node-role-attachment-AmazonEKSWorkerNodePolicy
        base:
          apiVersion: iam.aws.m.upbound.io/v1beta1
          kind: RolePolicyAttachment
          metadata:
            annotations:
              meta.upbound.io/example-id: iam/v1beta1/role
            name: karpenter-node-role-attachments-node-policy
          spec:
            forProvider:
              policyArn: arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
              roleRef:
                name: karpenter-node-role-placeholder
                namespace: crossplane-system-placeholder
            providerConfigRef:
              kind: ClusterProviderConfig
              name: default
        patches:
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.cluster_name
              strategy: string
              string:
                fmt: "karpenter-node-role-%s"
            toFieldPath: spec.forProvider.roleRef.name
          - type: FromCompositeFieldPath
            fromFieldPath: spec.upbound_namespace
            toFieldPath: metadata.namespace
          - type: FromCompositeFieldPath
            fromFieldPath: spec.upbound_namespace
            toFieldPath: spec.forProvider.roleRef.namespace

      - name: karpenter-node-role-attachment-AmazonEKS_CNI_Policy
        base:
          apiVersion: iam.aws.m.upbound.io/v1beta1
          kind: RolePolicyAttachment
          metadata:
            annotations:
              meta.upbound.io/example-id: iam/v1beta1/role
            name: karpenter-node-role-attachments-cni-policy
          spec:
            forProvider:
              policyArn: arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
              roleRef:
                name: karpenter-node-role-placeholder
                namespace: crossplane-system-placeholder
            providerConfigRef:
              kind: ClusterProviderConfig
              name: default
        patches:
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.cluster_name
              strategy: string
              string:
                fmt: "karpenter-node-role-%s"
            toFieldPath: spec.forProvider.roleRef.name  
          - type: FromCompositeFieldPath
            fromFieldPath: spec.upbound_namespace
            toFieldPath: metadata.namespace
          - type: FromCompositeFieldPath
            fromFieldPath: spec.upbound_namespace
            toFieldPath: spec.forProvider.roleRef.namespace

      - name: karpenter-node-role-attachment-AmazonEC2ContainerRegistryPullOnly
        base:
          apiVersion: iam.aws.m.upbound.io/v1beta1
          kind: RolePolicyAttachment
          metadata:
            annotations:
              meta.upbound.io/example-id: iam/v1beta1/role
            name: karpenter-node-role-attachments-registry-pull
          spec:
            forProvider:
              policyArn: arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPullOnly
              roleRef:
                name: karpenter-node-role-placeholder
                namespace: crossplane-system-placeholder
            providerConfigRef:
              kind: ClusterProviderConfig
              name: default
        patches:
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.cluster_name
              strategy: string
              string:
                fmt: "karpenter-node-role-%s"
            toFieldPath: spec.forProvider.roleRef.name  
          - type: FromCompositeFieldPath
            fromFieldPath: spec.upbound_namespace
            toFieldPath: metadata.namespace
          - type: FromCompositeFieldPath
            fromFieldPath: spec.upbound_namespace
            toFieldPath: spec.forProvider.roleRef.namespace

      - name: karpenter-node-role-attachment-AmazonSSMManagedInstanceCore
        base:
          apiVersion: iam.aws.m.upbound.io/v1beta1
          kind: RolePolicyAttachment
          metadata:
            annotations:
              meta.upbound.io/example-id: iam/v1beta1/role
            name: karpenter-node-role-attachments-instance-core
          spec:
            forProvider:
              policyArn: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
              roleRef:
                name: karpenter-node-role-placeholder
                namespace: crossplane-system-placeholder
            providerConfigRef:
              kind: ClusterProviderConfig
              name: default
        patches:
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.cluster_name
              strategy: string
              string:
                fmt: "karpenter-node-role-%s"
            toFieldPath: spec.forProvider.roleRef.name  
          - type: FromCompositeFieldPath
            fromFieldPath: spec.upbound_namespace
            toFieldPath: metadata.namespace
          - type: FromCompositeFieldPath
            fromFieldPath: spec.upbound_namespace
            toFieldPath: spec.forProvider.roleRef.namespace

  - step: eks-cluster-role
    functionRef:
      name: crossplane-contrib-function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - name: eks-cluster-role
        base:
          apiVersion: iam.aws.m.upbound.io/v1beta1
          kind: Role
          metadata:
            name: eks-cluster-role-placeholder
            namespace: upbound-placeholder
          spec:
            forProvider:
              assumeRolePolicy: |
                {
                    "Version": "2012-10-17",
                    "Statement": [
                        {
                            "Effect": "Allow",
                            "Principal": {
                                "Service": "eks.amazonaws.com"
                            },
                            "Action": [
                                "sts:AssumeRole",
                                "sts:TagSession"
                            ]
                        }
                    ]
                }

        patches:
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.cluster_name
              strategy: string
              string:
                fmt: "eks-cluster-role-%s"
            toFieldPath: metadata.name

          - type: FromCompositeFieldPath
            fromFieldPath: spec.upbound_namespace
            toFieldPath: metadata.namespace

  - step: eks-cluster-role-policy-attachments
    functionRef:
      name: crossplane-contrib-function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:

      - name: eks-cluster-role-attachment-cluster
        base:
          apiVersion: iam.aws.m.upbound.io/v1beta1
          kind: RolePolicyAttachment
          metadata:
            name: eks-cluster-role-attach-cluster-placeholder
            namespace: upbound-placeholder
          spec:
            forProvider:
              policyArn: arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
              roleRef:
                name: eks-cluster-role-placeholder
                namespace: upbound-placeholder
        patches:
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.cluster_name
              strategy: string
              string:
                fmt: "eks-cluster-role-%s"
            toFieldPath: spec.forProvider.roleRef.name

          - type: FromCompositeFieldPath
            fromFieldPath: spec.upbound_namespace
            toFieldPath: metadata.namespace

          - type: FromCompositeFieldPath
            fromFieldPath: spec.upbound_namespace
            toFieldPath: spec.forProvider.roleRef.namespace

      - name: eks-cluster-role-attachment-compute
        base:
          apiVersion: iam.aws.m.upbound.io/v1beta1
          kind: RolePolicyAttachment
          metadata:
            name: eks-cluster-role-attach-compute-placeholder
            namespace: upbound-placeholder
          spec:
            forProvider:
              policyArn: arn:aws:iam::aws:policy/AmazonEKSComputePolicy
              roleRef:
                name: eks-cluster-role-placeholder
                namespace: upbound-placeholder
        patches:
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.cluster_name
              strategy: string
              string:
                fmt: "eks-cluster-role-%s"
            toFieldPath: spec.forProvider.roleRef.name

          - type: FromCompositeFieldPath
            fromFieldPath: spec.upbound_namespace
            toFieldPath: metadata.namespace

          - type: FromCompositeFieldPath
            fromFieldPath: spec.upbound_namespace
            toFieldPath: spec.forProvider.roleRef.namespace

      - name: eks-cluster-role-attachment-networking
        base:
          apiVersion: iam.aws.m.upbound.io/v1beta1
          kind: RolePolicyAttachment
          metadata:
            name: eks-cluster-role-attach-networking-placeholder
            namespace: upbound-placeholder
          spec:
            forProvider:
              policyArn: arn:aws:iam::aws:policy/AmazonEKSNetworkingPolicy
              roleRef:
                name: eks-cluster-role-placeholder
                namespace: upbound-placeholder
        patches:
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.cluster_name
              strategy: string
              string:
                fmt: "eks-cluster-role-%s"
            toFieldPath: spec.forProvider.roleRef.name

          - type: FromCompositeFieldPath
            fromFieldPath: spec.upbound_namespace
            toFieldPath: metadata.namespace

          - type: FromCompositeFieldPath
            fromFieldPath: spec.upbound_namespace
            toFieldPath: spec.forProvider.roleRef.namespace

      - name: eks-cluster-role-attachment-blockstorage
        base:
          apiVersion: iam.aws.m.upbound.io/v1beta1
          kind: RolePolicyAttachment
          metadata:
            name: eks-cluster-role-attach-blockstorage-placeholder
            namespace: upbound-placeholder
          spec:
            forProvider:
              policyArn: arn:aws:iam::aws:policy/AmazonEKSBlockStoragePolicy
              roleRef:
                name: eks-cluster-role-placeholder
                namespace: upbound-placeholder
        patches:
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.cluster_name
              strategy: string
              string:
                fmt: "eks-cluster-role-%s"
            toFieldPath: spec.forProvider.roleRef.name

          - type: FromCompositeFieldPath
            fromFieldPath: spec.upbound_namespace
            toFieldPath: metadata.namespace

          - type: FromCompositeFieldPath
            fromFieldPath: spec.upbound_namespace
            toFieldPath: spec.forProvider.roleRef.namespace

      - name: eks-cluster-role-attachment-lb
        base:
          apiVersion: iam.aws.m.upbound.io/v1beta1
          kind: RolePolicyAttachment
          metadata:
            name: eks-cluster-role-attach-lb-placeholder
            namespace: upbound-placeholder
          spec:
            forProvider:
              policyArn: arn:aws:iam::aws:policy/AmazonEKSLoadBalancingPolicy
              roleRef:
                name: eks-cluster-role-placeholder
                namespace: upbound-placeholder
        patches:
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.cluster_name
              strategy: string
              string:
                fmt: "eks-cluster-role-%s"
            toFieldPath: spec.forProvider.roleRef.name

          - type: FromCompositeFieldPath
            fromFieldPath: spec.upbound_namespace
            toFieldPath: metadata.namespace

          - type: FromCompositeFieldPath
            fromFieldPath: spec.upbound_namespace
            toFieldPath: spec.forProvider.roleRef.namespace
