
#IMPORTANT: depends on the vpc being created first
#TODO: Impelement status fields to export the SG IDs
#TODO: REMOVE USE REF ONLY GROUP IDS:
          # - type: FromCompositeFieldPath
          #   fromFieldPath: status.eksClusterSecurityGroupId
          #   toFieldPath: spec.forProvider.groupId

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: awsinfra-sg
spec:
  compositeTypeRef:
    apiVersion: aws.kfo.io/v1alpha1
    kind: awsinfra

  mode: Pipeline

  pipeline:
  - step: sg-creation
    functionRef:
      name: crossplane-contrib-function-patch-and-transform

    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources

      patchSets:
        - name: common-aws-fields
          patches:
            - type: FromCompositeFieldPath
              fromFieldPath: spec.aws_region
              toFieldPath: spec.forProvider.region

      resources:
      - name: cluster-shared-node-sg
        base:
          apiVersion: ec2.aws.m.upbound.io/v1beta1
          kind: SecurityGroup
          metadata:
            labels:
              name: placeholder
            name: cluster-shared-node-sg-placeholder
            namespace: crossplane-system
          spec:
            forProvider:
              description: "Communication between all nodes in the cluster"
              vpcIdRef:
                name: vpc-id-ref-placeholder
                namespace: crossplane-system
              tags:
                Name: placeholder
        patches:
          - type: PatchSet
            patchSetName: common-aws-fields
          
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.cluster_name
              strategy: string
              string:
                fmt: "vpc-%s"
            toFieldPath: spec.forProvider.vpcIdRef.name
          - type: FromCompositeFieldPath
            fromFieldPath: spec.upbound_namespace
            toFieldPath: spec.forProvider.vpcIdRef.namespace

          # Name tag
          - type: CombineFromComposite
            toFieldPath: spec.forProvider.tags[Name]
            combine:
              strategy: string
              string:
                fmt: "%s-ClusterSharedNodeSecurityGroup"
              variables:
                - fromFieldPath: spec.cluster_name

          - type: CombineFromComposite
            toFieldPath: metadata.name
            combine:
              strategy: string
              string:
                fmt: "%s-cluster-shared-node-security-group"
              variables:
                - fromFieldPath: spec.cluster_name       

          - type: CombineFromComposite
            toFieldPath: metadata.labels[name]
            combine:
              strategy: string
              string:
                fmt: "%s-ClusterSharedNodeSecurityGroup"
              variables:
                - fromFieldPath: spec.cluster_name                

          - type: ToCompositeFieldPath
            fromFieldPath: status.atProvider.id
            toFieldPath: status.clusterSharedNodeSGId


      - name: control-plane-sg
        base:
          apiVersion: ec2.aws.m.upbound.io/v1beta1
          kind: SecurityGroup
          metadata:
            labels:
              name: placeholder
            name: control-plane-sg-placeholder
            namespace: crossplane-system
          spec:
            forProvider:
              description: "Communication between the control plane and worker nodegroups"
              vpcIdRef:
                name: vpc-id-ref-placeholder
                namespace: crossplane-system
              tags:
                Name: placeholder
        patches:
          - type: PatchSet
            patchSetName: common-aws-fields
          
          - type: CombineFromComposite
            combine:
              variables:
                - fromFieldPath: spec.cluster_name
              strategy: string
              string:
                fmt: "vpc-%s"
            toFieldPath: spec.forProvider.vpcIdRef.name
          - type: FromCompositeFieldPath
            fromFieldPath: spec.upbound_namespace
            toFieldPath: spec.forProvider.vpcIdRef.namespace

          - type: CombineFromComposite
            toFieldPath: spec.forProvider.tags[Name]
            combine:
              strategy: string
              string:
                fmt: "%s-ControlPlaneSecurityGroup"
              variables:
                - fromFieldPath: spec.cluster_name

          - type: CombineFromComposite
            toFieldPath: metadata.name
            combine:
              strategy: string
              string:
                fmt: "%s-control-plane-security-group"
              variables:
                - fromFieldPath: spec.cluster_name       

          - type: CombineFromComposite
            toFieldPath: metadata.labels[name]
            combine:
              strategy: string
              string:
                fmt: "%s-ControlPlaneSecurityGroup"
              variables:
                - fromFieldPath: spec.cluster_name                

          - type: ToCompositeFieldPath
            fromFieldPath: status.atProvider.id
            toFieldPath: status.clusterSharedNodeSGId
     
     
      - name: ingress-defaultcluster-to-node1
        base:
          apiVersion: ec2.aws.m.upbound.io/v1beta1
          kind: SecurityGroupIngressRule
          metadata:
            name: example
            namespace: upbound-system
          spec:
            forProvider:
              referencedSecurityGroupIdRef:
                name: eks-dsmm-test2-cluster-shared-node-security-group
                namespace: crossplane-system
              fromPort: -1
              ipProtocol: "-1"
              region: us-east-1              
              securityGroupIdSelector:
                matchControllerRef: true
                matchLabels:
                  name: placeholder
              toPort: -1
        
        patches:

          - type: PatchSet
            patchSetName: common-aws-fields        
                  
          - type: FromCompositeFieldPath
            fromFieldPath: spec.upbound_namespace
            toFieldPath: metadata.namespace
          
          - type: CombineFromComposite
            toFieldPath: metadata.name
            combine:
              strategy: string
              string:
                fmt: "%s-shared-node-sg-ingress-1"
              variables:
                - fromFieldPath: spec.cluster_name     

          - type: CombineFromComposite
            toFieldPath: spec.forProvider.securityGroupIdSelector.matchLabels[name]
            combine:
              strategy: string
              string:
                fmt: "%s-ClusterSharedNodeSecurityGroup"
              variables:
                - fromFieldPath: spec.cluster_name           

          - type: CombineFromComposite
            toFieldPath: spec.forProvider.referencedSecurityGroupIdRef.name
            combine:
              strategy: string
              string:
                fmt: "%s-cluster-shared-node-security-group"
              variables:
                - fromFieldPath: spec.cluster_name

          - type: FromCompositeFieldPath
            fromFieldPath: spec.upbound_namespace
            toFieldPath: spec.forProvider.referencedSecurityGroupIdRef.namespace

     #TODO: IMPORTANT! find a way to use the eks generated SG instead of use ciderules that allow all traffic 
      - name: ingress-defaultcluster-to-node2
        base:
          apiVersion: ec2.aws.m.upbound.io/v1beta1
          kind: SecurityGroupIngressRule
          metadata:
            name: example
            namespace: upbound-system
          spec:
            forProvider:
              cidrIpv4: 0.0.0.0/0 #FIXME
              fromPort: -1
              ipProtocol: "-1"
              region: us-east-1              
              securityGroupIdSelector:
                matchControllerRef: true
                matchLabels:
                  name: placeholder
              toPort: -1
        
        patches:

          - type: PatchSet
            patchSetName: common-aws-fields        
                  
          - type: FromCompositeFieldPath
            fromFieldPath: spec.upbound_namespace
            toFieldPath: metadata.namespace
          
          - type: CombineFromComposite
            toFieldPath: metadata.name
            combine:
              strategy: string
              string:
                fmt: "%s-shared-node-sg-ingress-2"
              variables:
                - fromFieldPath: spec.cluster_name     

          - type: CombineFromComposite
            toFieldPath: spec.forProvider.securityGroupIdSelector.matchLabels[name]
            combine:
              strategy: string
              string:
                fmt: "%s-ClusterSharedNodeSecurityGroup"
              variables:
                - fromFieldPath: spec.cluster_name          


      - name: egress-defaultcluster-to-node
        base:
          apiVersion: ec2.aws.m.upbound.io/v1beta1
          kind: SecurityGroupEgressRule
          metadata:
            name: example
            namespace: upbound-system
          spec:
            forProvider:
              cidrIpv4: 0.0.0.0/0
              fromPort: -1
              ipProtocol: "-1"
              region: us-east-1              
              securityGroupIdSelector:
                matchControllerRef: true
                matchLabels:
                  name: placeholder
              toPort: -1
        
        patches:

          - type: PatchSet
            patchSetName: common-aws-fields        
                  
          - type: FromCompositeFieldPath
            fromFieldPath: spec.upbound_namespace
            toFieldPath: metadata.namespace
          
          - type: CombineFromComposite
            toFieldPath: metadata.name
            combine:
              strategy: string
              string:
                fmt: "%s-shared-node-sg-egress-1"
              variables:
                - fromFieldPath: spec.cluster_name     

          - type: CombineFromComposite
            toFieldPath: spec.forProvider.securityGroupIdSelector.matchLabels[name]
            combine:
              strategy: string
              string:
                fmt: "%s-ClusterSharedNodeSecurityGroup"
              variables:
                - fromFieldPath: spec.cluster_name                      



      - name: egress-controlplane
        base:
          apiVersion: ec2.aws.m.upbound.io/v1beta1
          kind: SecurityGroupEgressRule
          metadata:
            name: example
            namespace: upbound-system
          spec:
            forProvider:
              cidrIpv4: 0.0.0.0/0
              fromPort: -1
              ipProtocol: "-1"
              region: us-east-1              
              securityGroupIdSelector:
                matchControllerRef: true
                matchLabels:
                  name: placeholder
              toPort: -1
        
        patches:

          - type: PatchSet
            patchSetName: common-aws-fields        
                  
          - type: FromCompositeFieldPath
            fromFieldPath: spec.upbound_namespace
            toFieldPath: metadata.namespace
          
          - type: CombineFromComposite
            toFieldPath: metadata.name
            combine:
              strategy: string
              string:
                fmt: "%s-control-plane-sg-egress-1"
              variables:
                - fromFieldPath: spec.cluster_name     

          - type: CombineFromComposite
            toFieldPath: spec.forProvider.securityGroupIdSelector.matchLabels[name]
            combine:
              strategy: string
              string:
                fmt: "%s-ControlPlaneSecurityGroup"
              variables:
                - fromFieldPath: spec.cluster_name                      
