apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: tekton-pipelines
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "xxx"
  AWS_SECRET_ACCESS_KEY: "xxx"
  AWS_DEFAULT_REGION: "us-east-1"

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-aws-runner
  namespace: tekton-pipelines
secrets:
  - name: aws-credentials


---

